/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'myviewport'
    },

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'form',
            autoScroll: true,
            height: 206,
            width: 710,
            bodyBorder: true,
            bodyPadding: 10,
            title: 'Registration',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 0,
                    height: 32,
                    width: 1070,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 0,
                            width: 389,
                            fieldLabel: 'Name'
                        },
                        {
                            xtype: 'datefield',
                            flex: 0,
                            width: 301,
                            fieldLabel: 'Birthday'
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    width: 1002,
                    fieldLabel: 'Address'
                },
                {
                    xtype: 'container',
                    flex: 0,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            width: 390,
                            fieldLabel: 'Contact Number'
                        },
                        {
                            xtype: 'textfield',
                            width: 300,
                            fieldLabel: 'Email Address'
                        }
                    ]
                },
                {
                    xtype: 'radiogroup',
                    width: 712,
                    fieldLabel: 'Gender',
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: 'Male'
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: 'Female'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 0,
                    width: 496,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            width: 118,
                            text: 'Register'
                        }
                    ]
                }
            ]
        }
    ]

});