DROP TABLE DEMO_CUSTOMER CASCADE CONSTRAINTS PURGE;
DROP TABLE stock CASCADE CONSTRAINTS PURGE;
DROP TABLE StokDetail CASCADE CONSTRAINTS PURGE;
DROP TABLE DEMO_ITEM CASCADE CONSTRAINTS PURGE;
DROP TABLE DEMO_CATEGORY CASCADE CONSTRAINTS PURGE;
DROP TABLE DEMO_ORDER CASCADE CONSTRAINTS PURGE;
DROP TABLE CATEGAORY_ITEM CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE SEQ_CUSTOMER_SEQUENCE;
DROP SEQUENCE SEQ_ORDER_SEQUENCE;

DROP SEQUENCE SEQ_stock_SEQUENCE;
DROP SEQUENCE SEQ_stock_detail_SEQUENCE;

DROP SEQUENCE SEQ_ITEM_SEQUENCE;
DROP SEQUENCE SEQ_CATEGORY_SEQUENCE;

COMMIT;