/*
 * File: app/view/windowMainPage.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KatchyCars.view.windowMainPage', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowMainPage',

    requires: [
        'KatchyCars.view.windowMainPageViewModel',
        'KatchyCars.view.windowMainPageViewController',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer',
        'Ext.form.Label',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.form.field.Text',
        'Ext.grid.View',
        'Ext.grid.plugin.RowEditing',
        'Ext.selection.RowModel',
        'Ext.form.FieldSet',
        'Ext.Img'
    ],

    controller: 'windowmainpage',
    viewModel: {
        type: 'windowmainpage'
    },
    height: 829,
    id: 'windowMainPage',
    itemId: 'windowMainPage',
    width: 857,
    closable: false,
    title: 'Main Page',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'tbspacer',
                    width: 360
                },
                {
                    xtype: 'label',
                    text: 'Katchy Cars'
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'tbspacer',
                    width: 190
                },
                {
                    xtype: 'button',
                    id: 'btnBuy',
                    itemId: 'btnBuy',
                    width: 90,
                    text: 'Buy'
                },
                {
                    xtype: 'button',
                    id: 'btnSell',
                    itemId: 'btnSell',
                    width: 100,
                    text: 'Sell  New Item'
                },
                {
                    xtype: 'button',
                    id: 'btnDelete',
                    itemId: 'btnDelete',
                    width: 100,
                    text: 'Remove Item'
                },
                {
                    xtype: 'button',
                    id: 'btnLogout',
                    itemId: 'btnLogout',
                    width: 80,
                    text: 'Logout'
                },
                {
                    xtype: 'button',
                    id: 'btnExit',
                    itemId: 'btnExit',
                    width: 80,
                    text: 'Exit'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            id: 'gridCarsForSale',
            title: 'Cars for Sale:',
            store: 'carStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'carManufacturer',
                    text: 'Manufacturer',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'carModel',
                    text: 'Model',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'carYear',
                    text: 'Year',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'carColor',
                    text: 'Color',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'carTransimission',
                    text: 'Transmission',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'carFuel',
                    text: 'Fuel',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'carPrice',
                    text: 'Price',
                    editor: {
                        xtype: 'textfield'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    width: 151,
                    dataIndex: 'carSellerName',
                    text: 'Seller',
                    flex: 1,
                    editor: {
                        xtype: 'textfield'
                    }
                }
            ],
            plugins: [
                {
                    ptype: 'rowediting',
                    pluginId: 'carGridRowEditing'
                }
            ],
            selModel: {
                selType: 'rowmodel'
            },
            listeners: {
                rowclick: 'onGridCarsForSaleRowClick'
            }
        },
        {
            xtype: 'panel',
            height: 320,
            id: 'panelCarDetails',
            itemId: 'panelCarDetails',
            title: 'Car Details',
            layout: {
                type: 'vbox',
                align: 'stretch',
                padding: 10
            },
            items: [
                {
                    xtype: 'fieldset',
                    flex: 1,
                    height: 254,
                    layout: 'auto',
                    title: 'My Fields',
                    items: [
                        {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'tbspacer'
                                },
                                {
                                    xtype: 'label',
                                    text: 'Manufacturer:'
                                },
                                {
                                    xtype: 'label',
                                    id: 'lblCarManufacturer',
                                    itemId: 'lblCarManufacturer',
                                    text: ''
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Model:'
                                },
                                {
                                    xtype: 'label',
                                    id: 'lblCarModel',
                                    itemId: 'lblCarModel',
                                    text: ''
                                },
                                {
                                    xtype: 'tbspacer'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Year:'
                                },
                                {
                                    xtype: 'label',
                                    id: 'lblCarYear',
                                    itemId: 'lblCarYear',
                                    text: ''
                                },
                                {
                                    xtype: 'tbspacer'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Color:'
                                },
                                {
                                    xtype: 'label',
                                    id: 'lblCarColor',
                                    itemId: 'lblCarColor',
                                    text: ''
                                },
                                {
                                    xtype: 'tbspacer'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Transmission:'
                                },
                                {
                                    xtype: 'label',
                                    id: 'lblCarTransmission',
                                    itemId: 'lblCarTransmission',
                                    text: ''
                                },
                                {
                                    xtype: 'tbspacer'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Fuel:'
                                },
                                {
                                    xtype: 'label',
                                    id: 'lblCarFuel',
                                    itemId: 'lblCarFuel',
                                    text: ''
                                },
                                {
                                    xtype: 'tbspacer'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Price:'
                                },
                                {
                                    xtype: 'label',
                                    id: 'lblCarPrice',
                                    itemId: 'lblCarPrice',
                                    text: ''
                                },
                                {
                                    xtype: 'tbspacer'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Seller:'
                                },
                                {
                                    xtype: 'label',
                                    id: 'lblCarSeller',
                                    itemId: 'lblCarSeller',
                                    text: ''
                                },
                                {
                                    xtype: 'tbspacer'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'image',
            height: 307,
            width: 854,
            src: 'data/2.jpg'
        }
    ]

});