/*
 * File: app/view/windowHomePage.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KatchyCars.view.windowHomePage', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowhomepage',

    requires: [
        'KatchyCars.view.windowHomePageViewModel',
        'Ext.Img',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'windowhomepage'
    },
    height: 543,
    id: 'windowHomePage',
    itemId: 'windowHomePage',
    width: 846,
    closable: false,
    title: 'Home Page',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'image',
            height: 484,
            width: 414,
            src: 'data/model_1.jpg'
        },
        {
            xtype: 'button',
            id: 'btnProceed',
            itemId: 'btnProceed',
            text: 'Click here to Proceed! <3'
        }
    ]

});