/*
 * File: app/view/UserWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KanenOnlineShopping.view.UserWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    height: 323,
    id: 'UserWindow',
    itemId: 'UserWindow',
    width: 486,
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    id: 'fullNameField',
                    itemId: 'fullNameField',
                    width: 316,
                    fieldLabel: 'Full Name'
                },
                {
                    xtype: 'textfield',
                    id: 'emailField',
                    width: 316,
                    fieldLabel: 'Email'
                },
                {
                    xtype: 'textfield',
                    id: 'addressField',
                    width: 316,
                    fieldLabel: 'Address'
                },
                {
                    xtype: 'textfield',
                    id: 'mobileNumberField',
                    itemId: 'mobileNumberField',
                    width: 316,
                    fieldLabel: 'Mobile Number'
                },
                {
                    xtype: 'textfield',
                    id: 'passwordField',
                    itemId: 'passwordField',
                    width: 316,
                    fieldLabel: 'Old Password'
                },
                {
                    xtype: 'textfield',
                    id: 'passwordField1',
                    itemId: 'passwordField1',
                    width: 316,
                    fieldLabel: 'New Password'
                },
                {
                    xtype: 'textfield',
                    id: 'confirmPasswordField',
                    itemId: 'confirmPasswordField',
                    width: 315,
                    fieldLabel: 'Confirm New Password'
                },
                {
                    xtype: 'toolbar',
                    height: 46,
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'Reset'
                        },
                        {
                            xtype: 'button',
                            id: 'btnUpdateFields',
                            itemId: 'btnUpdateFields',
                            text: 'Update'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});