/*
 * File: app/view/MyForm.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myform',

    requires: [
        'MyApp.view.MyFormViewModel',
        'Ext.form.field.Date',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'myform'
    },
    autoScroll: true,
    height: 443,
    width: 400,
    layout: 'auto',
    bodyPadding: 10,
    closable: true,
    title: 'Registration',

    items: [
        {
            xtype: 'textfield',
            width: 361,
            fieldLabel: 'Name:'
        },
        {
            xtype: 'textfield',
            width: 361,
            fieldLabel: 'Address:'
        },
        {
            xtype: 'textfield',
            width: 360,
            fieldLabel: 'Phone Number'
        },
        {
            xtype: 'datefield',
            width: 362,
            fieldLabel: 'Date of Birth:'
        },
        {
            xtype: 'radiogroup',
            fieldLabel: 'Gender',
            items: [
                {
                    xtype: 'radiofield',
                    boxLabel: 'Male'
                },
                {
                    xtype: 'radiofield',
                    boxLabel: 'Female'
                }
            ]
        },
        {
            xtype: 'textfield',
            width: 361,
            fieldLabel: 'Email Address:'
        },
        {
            xtype: 'textfield',
            maskElement: '*',
            width: 360,
            fieldLabel: 'Password:'
        },
        {
            xtype: 'textfield',
            maskElement: '*',
            width: 360,
            fieldLabel: 'Confirm Password:'
        },
        {
            xtype: 'button',
            width: 375,
            text: 'Register'
        }
    ]

});