/*
 * File: app/store/BookStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BMS.store.BookStore', {
    extend: 'Ext.data.Store',

    requires: [
        'BMS.model.BookModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'BMS.model.BookModel',
            storeId: 'BookStore',
            data: [
                {
                    title: 'Repudiandae Ad',
                    author: 'nihil',
                    publisher: 'fugiat',
                    category: 'ex',
                    datepublished: '04/13/1995'
                },
                {
                    title: 'Blanditiis Nihil A Voluptate',
                    author: 'nobis',
                    publisher: 'ipsum',
                    category: 'repudiandae',
                    datepublished: '07/18/1999'
                },
                {
                    title: 'Vel Qui Enim',
                    author: 'aut',
                    publisher: 'nisi',
                    category: 'ex',
                    datepublished: '07/29/2000'
                },
                {
                    title: 'Nostrum Modi',
                    author: 'vero',
                    publisher: 'culpa',
                    category: 'dolor',
                    datepublished: '07/10/1998'
                },
                {
                    title: 'Autem Explicabo Magni Unde',
                    author: 'quis',
                    publisher: 'aut',
                    category: 'quo',
                    datepublished: '09/10/2009'
                }
            ]
        }, cfg)]);
    }
});