/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BMS.view.MyWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.form.field.Date',
        'Ext.grid.plugin.RowEditing',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    height: 500,
    id: 'mainPage',
    itemId: 'mainPage',
    width: 1000,
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 150,
                    padding: '',
                    bodyPadding: 10,
                    title: 'Book Management System ',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'title',
                            itemId: 'title',
                            width: 591,
                            fieldLabel: 'Title'
                        },
                        {
                            xtype: 'textfield',
                            id: 'category',
                            itemId: 'category',
                            width: 591,
                            fieldLabel: 'Category:'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    id: 'gridView',
                    itemId: 'gridView',
                    title: 'Book List',
                    store: 'BookStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            id: 'titleGrid',
                            itemId: 'titleGrid',
                            dataIndex: 'title',
                            text: 'Title',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            id: 'authorGrid',
                            itemId: 'authorGrid',
                            dataIndex: 'author',
                            text: 'Author',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            id: 'publisherGrid',
                            itemId: 'publisherGrid',
                            dataIndex: 'publisher',
                            text: 'Publisher',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            id: 'categoryGrid',
                            itemId: 'categoryGrid',
                            dataIndex: 'category',
                            text: 'Category',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'datecolumn',
                            id: 'dateGrid',
                            itemId: 'dateGrid',
                            width: 100,
                            dataIndex: 'datepublished',
                            text: 'Date Published',
                            flex: 1,
                            editor: {
                                xtype: 'datefield'
                            }
                        }
                    ],
                    plugins: [
                        Ext.create('Ext.grid.plugin.RowEditing', {

                        })
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 30,
                                    id: 'btnCreate',
                                    itemId: 'btnCreate',
                                    width: 100,
                                    text: 'Create'
                                },
                                {
                                    xtype: 'button',
                                    height: 30,
                                    id: 'btnDelete',
                                    width: 100,
                                    text: 'Delete'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            layout: {
                                type: 'hbox',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    height: 30,
                                    id: 'btnLogout',
                                    itemId: 'btnLogout',
                                    width: 100,
                                    text: 'Logout'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});