/*
 * File: app/store/productsStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KanenOnlineShopping.store.productsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'KanenOnlineShopping.model.Product'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'KanenOnlineShopping.model.Product',
            storeId: 'productsStore',
            data: [
                {
                    productId: 1,
                    productName: 'Laptop 1',
                    productDescription: 'Laptop 1 ProductDescription',
                    productPrice: 901.00,
                    productStockQuantity: 10,
                    productImagePath: 'resource/laptop.png'
                },
                {
                    productId: 2,
                    productName: 'Laptop 2',
                    productDescription: 'Laptop 2 ProductDescription',
                    productPrice: 859.00,
                    productStockQuantity: 20,
                    productImagePath: 'resource/laptop2.jpg'
                },
                {
                    productId: 3,
                    productName: 'Laptop 3',
                    productDescription: 'Laptop 3 ProductDescription',
                    productPrice: 107.00,
                    productStockQuantity: 13,
                    productImagePath: 'resource/laptop3.jpg'
                },
                {
                    productId: 4,
                    productName: 'Phone 1',
                    productDescription: 'Phone 1ProductDescription',
                    productPrice: 654.00,
                    productStockQuantity: 5,
                    productImagePath: 'resource/phone.jpg'
                },
                {
                    productId: 5,
                    productName: 'Phone4',
                    productDescription: 'ProductDescription 5',
                    productPrice: 229.00,
                    productStockQuantity: 721,
                    productImagePath: 'resource/phone4.jpg'
                }
            ]
        }, cfg)]);
    }
});