/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BMS.controller.LoginController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'frmLogin',
            selector: '#frmLogin'
        },
        {
            ref: 'frmReg',
            selector: '#frmReg'
        },
        {
            ref: 'mainPage',
            selector: '#mainPage'
        }
    ],

    onLoginClick: function(button, e, eOpts) {
        var username, password, store, arrayStore;
        username = Ext.getCmp('lusername');
        password = Ext.getCmp('lpassword');
        store = Ext.StoreManager.get('UserStore');
        arrayStore = store.data.items;
        var self = this;
        var isValid = false;
        //put each item into record
        Ext.each(arrayStore, function(record){
            if(username.getValue() == record.data.username && password.getValue() == record.data.password){
                isValid = true;
            self.frmLogin.hide();
            self.mainPage.show();
            }
        });


        if(!isValid){
            Ext.Msg.alert('Warning', 'Unable to log in. Check username or password.');
        }
    },

    onLbtnRegClick: function() {
         this.getFrmLogin().setVisible(false);
        this.getFrmReg().setVisible(true);
    },

    onLaunch: function() {
            this.frmLogin = this.getFrmLogin();
            this.mainPage = Ext.create('BMS.view.MyWindow');
    },

    init: function(application) {
        this.control({
            "#lbtnLog": {
                click: this.onLoginClick
            },
            "#lbtnReg": {
                click: this.onLbtnRegClick
            }
        });
    }

});
