/*
 * File: app/view/itemContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KanenOnlineShopping.view.itemContainer', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.Img',
        'Ext.form.Label',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    border: '2 px solid black',
    height: 385,
    margin: '',
    width: 287,

    layout: {
        type: 'vbox',
        align: 'center',
        defaultMargins: {
            top: 0,
            right: 0,
            bottom: 0,
            left: 0
        },
        padding: 10
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'image',
                    height: 224,
                    width: 233,
                    src: 'resource/laptop.png'
                },
                {
                    xtype: 'label',
                    margins: '4',
                    height: 19,
                    width: 180,
                    text: 'My Label'
                },
                {
                    xtype: 'tbspacer',
                    flex: 1,
                    height: 150,
                    width: 90
                },
                {
                    xtype: 'button',
                    width: 87,
                    text: 'Add to Cart',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        KanenOnlineShopping.app.getController('productController').addItemToCart(this.productId,this.productName,this.productDescription,this.productPrice,this.productStockQuantity,this.productImagePath);
    }

});