/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.form.field.Number',
        'Ext.grid.View',
        'Ext.selection.RowModel',
        'Ext.grid.plugin.RowEditing',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox'
    ],

    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    height: 785,
                    id: 'loginContainer',
                    itemId: 'loginContainer',
                    style: 'background: url(resource/melvin.jpg) no-repeat center center fixed;\n-webkit-background-size: cover;\n  -moz-background-size: cover;\n  -o-background-size: cover;\n  background-size: cover;',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'form',
                            height: 172,
                            width: 418,
                            bodyPadding: 10,
                            title: 'Login',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'txtUsername',
                                    itemId: 'txtUsername',
                                    fieldLabel: 'Username',
                                    allowBlank: false,
                                    emptyText: 'Username'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'txtPassword',
                                    itemId: 'txtPassword',
                                    fieldLabel: 'Password',
                                    inputType: 'password',
                                    emptyText: 'Password'
                                },
                                {
                                    xtype: 'container',
                                    id: 'ContainerBtn',
                                    itemId: 'ContainerBtn',
                                    width: 355,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            height: 20,
                                            id: 'btnLogin',
                                            itemId: 'btnLogin',
                                            margin: 10,
                                            width: 150,
                                            text: 'Login'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 775,
                    id: 'adminContainer',
                    itemId: 'adminContainer',
                    layout: 'border',
                    items: [
                        {
                            xtype: 'container',
                            region: 'north',
                            height: 94,
                            itemId: 'TopContainer',
                            style: 'background-color:#201303',
                            layout: 'border'
                        },
                        {
                            xtype: 'container',
                            region: 'west',
                            itemId: 'LeftContainer',
                            style: 'background-color:#201303',
                            width: 253,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'container',
                                    height: 145,
                                    hidden: true,
                                    id: 'confirmCustomerContainer',
                                    itemId: 'confirmCustomerContainer',
                                    style: 'background-color:#00aadd',
                                    width: 207,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'button',
                                            height: 150,
                                            id: 'btnCustomerRequest',
                                            itemId: 'btnCustomerRequest',
                                            width: 186,
                                            text: 'Customer Requests'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    height: 145,
                                    hidden: true,
                                    id: 'updateOrderStatusContainer',
                                    itemId: 'updateOrderStatusContainer',
                                    width: 206,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'confirmOrderBtn',
                                            itemId: 'confirmOrderBtn',
                                            text: 'Pending Orders'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    height: 145,
                                    hidden: true,
                                    id: 'viewAllOrderbtnContainer',
                                    itemId: 'viewAllOrderbtnContainer',
                                    width: 206,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'viewAllOrderBtn',
                                            itemId: 'viewAllOrderBtn',
                                            text: 'View All Orders'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'menu',
                                    floating: false,
                                    width: 120,
                                    bodyStyle: 'background-color:#ffffff !important;',
                                    animCollapse: true,
                                    collapseDirection: 'left',
                                    collapsed: false,
                                    collapsible: true,
                                    glyph: '',
                                    overlapHeader: false,
                                    placeholderCollapseHideMode: 2,
                                    titleAlign: 'center',
                                    titleCollapse: false,
                                    ignoreParentClicks: true,
                                    items: [
                                        {
                                            xtype: 'menuitem',
                                            height: 45,
                                            id: 'products',
                                            itemId: 'products',
                                            defaultAlign: 'center',
                                            glyph: '',
                                            iconCls: '',
                                            menuAlign: 'center',
                                            text: 'Products'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            height: 45,
                                            id: 'membershipRequest',
                                            itemId: 'membershipRequest',
                                            text: 'Membership Requests'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            height: 45,
                                            id: 'orderReqeust',
                                            itemId: 'orderReqeust',
                                            text: 'Order Requests'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            height: 45,
                                            id: 'viewAllOrder',
                                            itemId: 'viewAllOrder',
                                            text: 'View All Orders'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            height: 45,
                                            text: 'FAQ\'s'
                                        },
                                        {
                                            xtype: 'menuitem',
                                            height: 45,
                                            id: 'logout',
                                            itemId: 'logout',
                                            text: 'Logout'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            region: 'center',
                            itemId: 'CenterContainer',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    id: 'productListPanel',
                                    itemId: 'productListPanel',
                                    title: 'Products',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            id: 'productListGrid',
                                            itemId: 'productListGrid',
                                            title: '',
                                            store: 'product',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'productId',
                                                    text: 'Product Id',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'productName',
                                                    text: 'Product Name',
                                                    flex: 1,
                                                    editor: {
                                                        xtype: 'textfield'
                                                    }
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'productDescription',
                                                    text: 'Product Description',
                                                    flex: 2,
                                                    editor: {
                                                        xtype: 'textfield'
                                                    }
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'productPrice',
                                                    text: 'Price',
                                                    flex: 1,
                                                    editor: {
                                                        xtype: 'numberfield'
                                                    }
                                                }
                                            ],
                                            selModel: Ext.create('Ext.selection.RowModel', {

                                            }),
                                            plugins: [
                                                Ext.create('Ext.grid.plugin.RowEditing', {

                                                })
                                            ]
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'bottom',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    id: 'btnAddProduct',
                                                    itemId: 'btnAddProduct',
                                                    text: 'Add Product'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'btnUpdateProduct',
                                                    itemId: 'btnUpdateProduct',
                                                    text: 'Update Product'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    id: 'viewAllOrderPanel',
                                    itemId: 'viewAllOrderPanel',
                                    layout: 'fit',
                                    title: 'Transactions',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            id: 'viewAllOrderGrid',
                                            itemId: 'viewAllOrderGrid',
                                            title: '',
                                            store: 'orderStore',
                                            columns: [
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'orderId',
                                                    text: 'Order Id',
                                                    flex: 1,
                                                    format: '00000'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'userFullName',
                                                    text: 'Name',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'orderDate',
                                                    text: 'Order Date',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'totalCost',
                                                    text: 'Total Cost',
                                                    flex: 1,
                                                    format: '00000'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'orderStatus',
                                                    text: 'Order Status',
                                                    flex: 1
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    id: 'orderRequestsPanel',
                                    itemId: 'orderRequestsPanel',
                                    layout: 'fit',
                                    title: 'Order Requests',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            height: 427,
                                            id: 'orderRequestsGrid',
                                            itemId: 'orderRequestsGrid',
                                            title: '',
                                            store: 'orderStore',
                                            columns: [
                                                {
                                                    xtype: 'numbercolumn',
                                                    id: 'orderId',
                                                    itemId: 'orderId',
                                                    width: 176,
                                                    dataIndex: 'orderId',
                                                    text: 'Order id',
                                                    flex: 1,
                                                    format: '00000'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    id: 'userId',
                                                    itemId: 'userId',
                                                    width: 141,
                                                    dataIndex: 'userFullName',
                                                    text: 'Name',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    id: 'orderDate',
                                                    itemId: 'orderDate',
                                                    width: 151,
                                                    dataIndex: 'orderDate',
                                                    text: 'Order Date',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    id: 'totalCost',
                                                    itemId: 'totalCost',
                                                    dataIndex: 'totalCost',
                                                    text: 'Total Cost',
                                                    flex: 1,
                                                    format: '00000'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    id: 'orderStatus',
                                                    itemId: 'orderStatus',
                                                    width: 212,
                                                    dataIndex: 'orderStatus',
                                                    text: 'Order Status',
                                                    flex: 1,
                                                    editor: {
                                                        xtype: 'combobox',
                                                        editable: false,
                                                        queryMode: 'local',
                                                        store: [
                                                            'Order Delivered'
                                                        ],
                                                        typeAhead: true
                                                    }
                                                }
                                            ],
                                            plugins: [
                                                Ext.create('Ext.grid.plugin.RowEditing', {

                                                })
                                            ],
                                            selModel: Ext.create('Ext.selection.RowModel', {

                                            })
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'bottom',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    id: 'btnSaveUpdates',
                                                    itemId: 'btnSaveUpdates',
                                                    width: 100,
                                                    text: 'Save Updates'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    id: 'customerConfirmPanel',
                                    itemId: 'customerConfirmPanel',
                                    layout: 'fit',
                                    title: 'Customer Requests',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            id: 'membershipRequestGrid',
                                            itemId: 'membershipRequestGrid',
                                            store: 'membershipRequest',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'fullName',
                                                    text: 'Name',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'currentMembershipLevel',
                                                    text: 'Current Membership Level',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'requestedMembershipLevel',
                                                    text: 'Requested Membership Level',
                                                    flex: 1
                                                }
                                            ],
                                            selModel: Ext.create('Ext.selection.RowModel', {

                                            })
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'bottom',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    id: 'btnApproveRequest',
                                                    width: 116,
                                                    text: 'Approve Request'
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'btnRejectRequest',
                                                    itemId: 'btnRejectRequest',
                                                    text: 'Reject Request'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    hidden: true,
                                    id: 'AddProductContainer',
                                    width: 150,
                                    items: [
                                        {
                                            xtype: 'form',
                                            height: 250,
                                            id: 'addProductForm',
                                            itemId: 'addProductForm',
                                            width: 575,
                                            bodyPadding: 10,
                                            title: 'Add Product',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Product Name',
                                                    labelWidth: 120
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Product Description',
                                                    labelWidth: 120
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Product Price',
                                                    labelWidth: 120,
                                                    regex: /^[1-9][0-9]*$/
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'In Stock Quantity',
                                                    labelWidth: 120,
                                                    regex: /^[1-9][0-9]*$/
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Image Path',
                                                    labelWidth: 120
                                                },
                                                {
                                                    xtype: 'container',
                                                    height: 25,
                                                    id: 'ButtonContainer',
                                                    itemId: 'ButtonContainer',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            margins: '',
                                                            height: 25,
                                                            margin: 2,
                                                            padding: 1,
                                                            width: 100,
                                                            text: 'Save Product'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            margin: 2,
                                                            width: 100,
                                                            text: 'Reset'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            margin: 2,
                                                            width: 100,
                                                            text: 'Cancel'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});