/*
 * File: app/view/ChangePassWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KanenOnlineShopping.view.ChangePassWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.field.Text',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    height: 340,
    hidden: false,
    id: 'ChangePassWindow',
    itemId: 'ChangePassWindow',
    width: 530,
    title: 'Change Password',
    modal: true,

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    id: 'oldPassword',
                    itemId: 'oldPassword',
                    width: 341,
                    fieldLabel: 'Old Password',
                    inputType: 'password',
                    allowBlank: false,
                    allowOnlyWhitespace: false
                },
                {
                    xtype: 'textfield',
                    id: 'newPassword',
                    itemId: 'newPassword',
                    width: 339,
                    fieldLabel: 'New Password',
                    inputType: 'password',
                    allowBlank: false,
                    allowOnlyWhitespace: false
                },
                {
                    xtype: 'textfield',
                    id: 'confirmNewPass',
                    itemId: 'confirmNewPass',
                    width: 341,
                    fieldLabel: 'Confirm New Password ',
                    inputType: 'password',
                    allowBlank: false,
                    allowOnlyWhitespace: false
                },
                {
                    xtype: 'tbspacer',
                    flex: 0
                },
                {
                    xtype: 'button',
                    height: 36,
                    id: 'btnResetPass',
                    itemId: 'btnResetPass',
                    width: 143,
                    text: 'Reset'
                },
                {
                    xtype: 'tbspacer',
                    flex: 0,
                    height: 10,
                    width: 46
                },
                {
                    xtype: 'button',
                    height: 39,
                    id: 'btnChangePassword',
                    itemId: 'btnChangePassword',
                    width: 142,
                    text: 'Change Password'
                }
            ]
        });

        me.callParent(arguments);
    }

});