/*
 * File: app/view/EmployeeInfo.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W3D4.view.EmployeeInfo', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.grid.column.Date',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar'
    ],

    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Employee Information:',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    title: 'Employee list:',
                                    store: 'employeeStore',
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            width: 120,
                                            dataIndex: 'id',
                                            text: 'ID',
                                            format: '0,000'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 151,
                                            defaultWidth: 120,
                                            dataIndex: 'firstname',
                                            text: 'First Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 177,
                                            defaultWidth: 120,
                                            dataIndex: 'middlename',
                                            text: 'Middle Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 197,
                                            defaultWidth: 120,
                                            dataIndex: 'lastname',
                                            text: 'Last Name'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: 159,
                                            defaultWidth: 120,
                                            dataIndex: 'birthdate',
                                            text: 'BirthDate',
                                            format: 'mm-dd-yyyy'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 162,
                                            defaultWidth: 120,
                                            dataIndex: 'city',
                                            text: 'City'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 140,
                                            defaultWidth: 120,
                                            dataIndex: 'state',
                                            text: 'State'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 514,
                            title: 'Create Employee',
                            items: [
                                {
                                    xtype: 'form',
                                    height: 426,
                                    id: 'employeeInfoForm',
                                    itemId: 'employeeInfoForm',
                                    bodyPadding: 10,
                                    title: 'Please fill up all required fields:',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 0.8,
                                            title: '',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch',
                                                defaultMargins: {
                                                    top: 0,
                                                    right: 0,
                                                    bottom: 0,
                                                    left: 0
                                                },
                                                padding: 10
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 0.6,
                                                    margins: '',
                                                    border: 'border: 5, style: {     borderColor: \'red\',     borderStyle: \'solid\' }',
                                                    height: 445,
                                                    margin: '',
                                                    padding: '',
                                                    width: 504,
                                                    layout: {
                                                        type: 'vbox',
                                                        defaultMargins: {
                                                            top: 0,
                                                            right: 0,
                                                            bottom: 0,
                                                            left: 0
                                                        },
                                                        padding: 10
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            itemId: 'empId',
                                                            margin: 10,
                                                            width: 103,
                                                            fieldLabel: 'ID',
                                                            labelWidth: 30
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            margins: '',
                                                            itemId: 'empFirstname',
                                                            margin: 10,
                                                            padding: '',
                                                            width: 309,
                                                            fieldLabel: 'First Name:',
                                                            labelWidth: 80
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            itemId: 'empMiddlename',
                                                            margin: 10,
                                                            fieldLabel: 'Middle Name:',
                                                            labelWidth: 80
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            itemId: 'empLastname',
                                                            margin: 10,
                                                            width: 357,
                                                            fieldLabel: 'Last Name:',
                                                            labelWidth: 80
                                                        },
                                                        {
                                                            xtype: 'datefield',
                                                            itemId: 'empBirthdate',
                                                            margin: 10,
                                                            fieldLabel: 'Birth Date:',
                                                            labelWidth: 80
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'vbox',
                                                        padding: 10
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textareafield',
                                                            itemId: 'empCity',
                                                            width: 523,
                                                            fieldLabel: 'City:'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            itemId: 'empState',
                                                            width: 390,
                                                            fieldLabel: 'State:'
                                                        }
                                                    ]
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    flex: 1,
                                                    dock: 'bottom',
                                                    layout: {
                                                        type: 'hbox',
                                                        pack: 'end'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'btnCreateEmployee',
                                                            width: 70,
                                                            text: 'Create'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            width: 70,
                                                            text: 'Clear'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    title: ''
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Table'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});