/*
 * File: app/store/orderStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.orderStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.orderModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MyApp.model.orderModel',
            storeId: 'orderStore',
            data: [
                {
                    orderId: 479,
                    userId: 90,
                    orderDate: 2005,
                    totalCost: 962.51,
                    orderStatus: 'On Delivery',
                    items: 'consequatur'
                },
                {
                    orderId: 780,
                    userId: 450,
                    orderDate: 1994,
                    totalCost: 477.84,
                    orderStatus: 'On Delivery',
                    items: 'enim'
                },
                {
                    orderId: 935,
                    userId: 708,
                    orderDate: 2000,
                    totalCost: 881.02,
                    orderStatus: 'minus',
                    items: 'On Delivery'
                },
                {
                    orderId: 780,
                    userId: 450,
                    orderDate: 1994,
                    totalCost: 477.84,
                    orderStatus: 'Order Approved',
                    items: 'enim'
                },
                {
                    orderId: 935,
                    userId: 708,
                    orderDate: 2000,
                    totalCost: 881.02,
                    orderStatus: 'Order Approved',
                    items: 'voluptatem'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});