/*
 * File: app/view/RegisterWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('KanenOnlineShopping.view.RegisterWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    draggable: false,
    height: 474,
    id: 'registerWindow',
    itemId: 'registerWindow',
    width: 626,
    resizable: false,
    layout: 'fit',
    closable: false,
    title: 'Registration',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 329,
                    id: 'frmRegister',
                    itemId: 'frmRegister',
                    padding: 10,
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            height: 30,
                            id: 'txtRegUsername',
                            itemId: 'txtRegUsername',
                            padding: 5,
                            fieldLabel: 'Username',
                            labelWidth: 150,
                            allowBlank: false,
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            height: 33,
                            id: 'txtRegPassword',
                            itemId: 'txtRegPassword',
                            padding: 5,
                            fieldLabel: 'Password',
                            labelWidth: 150,
                            inputType: 'password',
                            allowBlank: false,
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            height: 33,
                            id: 'txtRegConfirmPassword',
                            itemId: 'txtRegConfirmPassword',
                            padding: 5,
                            fieldLabel: 'Confirm Password',
                            labelWidth: 150,
                            inputType: 'password',
                            allowBlank: false,
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            height: 33,
                            id: 'txtRegFullname',
                            itemId: 'txtRegFullname',
                            padding: 5,
                            fieldLabel: 'Full Name',
                            labelWidth: 150,
                            allowBlank: false,
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            id: 'txtRegAddress',
                            itemId: 'txtRegAddress',
                            padding: 5,
                            fieldLabel: 'Address',
                            labelWidth: 150
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            height: 33,
                            id: 'txtRegEmail',
                            itemId: 'txtRegEmail',
                            padding: 5,
                            fieldLabel: 'E-mail Address',
                            labelWidth: 150,
                            inputType: 'email',
                            allowBlank: false,
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            height: 33,
                            id: 'txtRegContactNumber',
                            itemId: 'txtRegContactNumber',
                            padding: 5,
                            fieldLabel: 'Contact Number',
                            labelWidth: 150,
                            inputType: 'tel',
                            allowBlank: false,
                            allowOnlyWhitespace: false
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'tbspacer',
                                    width: 150
                                },
                                {
                                    xtype: 'button',
                                    height: 33,
                                    id: 'btnRegReset',
                                    itemId: 'btnRegReset',
                                    width: 130,
                                    text: 'Reset'
                                },
                                {
                                    xtype: 'button',
                                    height: 33,
                                    id: 'btnRegRegister',
                                    itemId: 'btnRegRegister',
                                    width: 130,
                                    text: 'Register'
                                },
                                {
                                    xtype: 'button',
                                    height: 33,
                                    id: 'btnRegCancel',
                                    itemId: 'btnRegCancel',
                                    width: 130,
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});